from typing import Protocol


class CalculationRepository(Protocol):
    def list(self) -> list[dict]: ...

    def add(self, calculation: dict) -> None: ...

    def replace_all(self, calculations: list[dict]) -> None: ...
